// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASeUPwk_-9mFILGWY0l165Uwqyql9azIY',
    appId: '1:215322873728:web:4098233a2a96cfdc123b65',
    messagingSenderId: '215322873728',
    projectId: 'apex-mouda',
    authDomain: 'apex-mouda.firebaseapp.com',
    storageBucket: 'apex-mouda.appspot.com',
    measurementId: 'G-TLLJ9MFM7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyHAaNd68igpaNkOUfTIBoPlW9z0ljDcE',
    appId: '1:215322873728:android:1834569e199acd10123b65',
    messagingSenderId: '215322873728',
    projectId: 'apex-mouda',
    storageBucket: 'apex-mouda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiNH1VArWiQFqdu7VMsAKuG3DKvRFqPfE',
    appId: '1:215322873728:ios:a8634e1f756d6b29123b65',
    messagingSenderId: '215322873728',
    projectId: 'apex-mouda',
    storageBucket: 'apex-mouda.appspot.com',
    iosClientId: '215322873728-58diis8amr50k79jctee54o7rlbncqvo.apps.googleusercontent.com',
    iosBundleId: 'com.example.apexMouda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiNH1VArWiQFqdu7VMsAKuG3DKvRFqPfE',
    appId: '1:215322873728:ios:eb45f50ec06b5f7e123b65',
    messagingSenderId: '215322873728',
    projectId: 'apex-mouda',
    storageBucket: 'apex-mouda.appspot.com',
    iosClientId: '215322873728-48tudgu25q046938ipr65n1v5fe3t6vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.apexMouda.RunnerTests',
  );
}
